//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zodiac.rc
//
#define IDR_MAIN_MENU                   101
#define IDD_MAIN_DLG                    102
#define IDD_MAIN                        102
#define IDD_OPTIONS                     103
#define IDI_ZODIAC                      104
#define IDB_ZODIAC                      108
#define IDD_WORD                        109
#define IDD_PATTERNS                    111
#define IDD_ANAGRAM                     113
#define IDD_ABOUT                       114
#define IDD_CIPHER                      115
#define IDD_TEXT                        115
#define IDD_MERGE                       116
#define IDD_INIT                        117
#define IDD_NUMBER                      117
#define IDD_GRAPHS                      118
#define IDD_STRING                      119
#define IDD_INITKEY                     120
#define IDD_SEQHOMO						121
#define IDR_ACCEL                       122
#define IDC_PLAIN                       1000
#define IDC_CIPHER                      1001
#define IDC_SOLVE                       1002
#define IDC_CHANGE                      1003
#define IDC_MAP_CHANGE                  1003
#define IDC_MAP                         1004
#define IDC_RELOAD                      1005
#define IDC_RESET                       1005
#define IDC_LTRFREQ                     1006
#define IDC_SWAPS                       1008
#define IDC_REVERT                      1009
#define IDC_MAP_VALUE                   1009
#define IDC_MAP_TITLE                   1010
#define IDC_WORD_MAX                    1010
#define IDC_USEBI                       1011
#define IDC_USETRI                      1012
#define IDC_USETETRA                    1013
#define IDC_USEPENTA                    1014
#define IDC_MAXFAIL                     1017
#define IDC_TIME                        1018
#define IDC_LINECHARS                   1018
#define IDC_TRY                         1019
#define IDC_EXTRA_LTR                   1019
#define IDC_FAIL                        1020
#define IDC_WORD_MIN                    1020
#define IDC_SCORE                       1021
#define IDC_DIFF                        1022
#define IDC_VOWEL                       1023
#define IDC_VOWEL_ACT                   1023
#define IDC_PROG                        1024
#define IDC_TRYTIME                     1024
#define IDC_VOWEL_EXP                   1024
#define IDC_ABOUT1                      1026
#define IDC_ABOUT                       1026
#define IDC_ABOUT2                      1027
#define IDC_WORD                        1027
#define IDC_ABOUT3                      1028
#define IDC_LANG                        1036
#define IDC_PATTERNS                    1037
#define IDC_TABLE                       1038
#define IDC_CIPHER_TITLE                1039
#define IDC_PAT_TITLE                   1040
#define IDC_SCROLL                      1041
#define IDC_SLIDER1                     1042
#define IDC_SCROLLBAR1                  1043
#define IDC_TS_UP                       1045
#define IDC_TS_DOWN                     1046
#define IDC_MERSYM1                     1047
#define IDC_MERSYM2                     1048
#define IDC_TEXTINFO                    1048
#define IDC_ANAGRAM                     1050
#define IDC_INIT                        1051
#define IDC_CIPHER_BORDER               1051
#define IDC_NUMBER                      1051
#define IDC_TS_TEXT                     1052
#define IDC_GRAPH                       1053
#define IDC_MAIN_TAB                    1054
#define IDC_SOLVE_TITLE                 1055
#define IDC_TIME_TITLE                  1056
#define IDC_TRY_TITLE                   1057
#define IDC_FAIL_TITLE                  1058
#define IDC_SCORE_TITLE                 1059
#define IDC_TABLE_TITLE                 1060
#define IDC_LTRFREQ_TITLE               1061
#define IDC_DIFF_TITLE                  1062
#define IDC_VOWEL_ACT_TITLE             1063
#define IDC_LTRFREQ_HEADER              1064
#define IDC_INIT_REM                    1064
#define IDC_STRING                      1065
#define IDC_WORD_TITLE                  1066
#define IDC_BUTTON1                     1066
#define IDC_WORD_LIST                   1067
#define IDC_INIT_A_EDIT                 1068
#define IDC_INIT_A_SPIN                 1069
#define IDC_INIT_B_EDIT                 1070
#define IDC_INIT_B_SPIN                 1071
#define IDC_INIT_C_EDIT                 1072
#define IDC_INIT_C_SPIN                 1073
#define IDC_INIT_D_EDIT                 1074
#define IDC_INIT_D_SPIN                 1075
#define IDC_INIT_E_EDIT                 1076
#define IDC_INIT_E_SPIN                 1077
#define IDC_INIT_F_EDIT                 1078
#define IDC_INIT_F_SPIN                 1079
#define IDC_INIT_G_EDIT                 1080
#define IDC_INIT_G_SPIN                 1081
#define IDC_INIT_H_EDIT                 1082
#define IDC_INIT_H_SPIN                 1083
#define IDC_INIT_I_EDIT                 1084
#define IDC_INIT_I_SPIN                 1085
#define IDC_INIT_J_EDIT                 1086
#define IDC_INIT_J_SPIN                 1087
#define IDC_INIT_K_EDIT                 1088
#define IDC_INIT_K_SPIN                 1089
#define IDC_INIT_L_EDIT                 1090
#define IDC_INIT_L_SPIN                 1091
#define IDC_INIT_M_EDIT                 1092
#define IDC_INIT_M_SPIN                 1093
#define IDC_INIT_N_EDIT                 1094
#define IDC_INIT_N_SPIN                 1095
#define IDC_INIT_O_EDIT                 1096
#define IDC_INIT_O_SPIN                 1097
#define IDC_INIT_P_EDIT                 1098
#define IDC_INIT_P_SPIN                 1099
#define IDC_INIT_Q_EDIT                 1100
#define IDC_INIT_Q_SPIN                 1101
#define IDC_INIT_R_EDIT                 1102
#define IDC_INIT_R_SPIN                 1103
#define IDC_INIT_S_EDIT                 1104
#define IDC_INIT_S_SPIN                 1105
#define IDC_INIT_T_EDIT                 1106
#define IDC_INIT_T_SPIN                 1107
#define IDC_INIT_U_EDIT                 1108
#define IDC_INIT_U_SPIN                 1109
#define IDC_INIT_V_EDIT                 1110
#define IDC_INIT_V_SPIN                 1111
#define IDC_INIT_W_EDIT                 1112
#define IDC_INIT_W_SPIN                 1113
#define IDC_INIT_X_EDIT                 1114
#define IDC_INIT_X_SPIN                 1115
#define IDC_INIT_Y_EDIT                 1116
#define IDC_INIT_Y_SPIN                 1117
#define IDC_INIT_Z_EDIT                 1118
#define IDC_INIT_Z_SPIN                 1119
#define IDC_INIT_TARGET_EDIT			1120
#define IDC_INIT_TARGET_SPIN			1121
#define IDC_HOMO_TOL_EDIT               1122
#define IDC_HOMO_TOL_SPIN               1123
#define IDC_HOMO_LEN_EDIT               1124
#define IDC_HOMO_LEN_SPIN               1125
#define IDC_HOMO_SETS                   1126
#define IDC_IOC_WEIGHT_EDIT             1127
#define IDC_IOC_WEIGHT_SPIN             1128
#define IDC_IOC_WEIGHT_TITLE			1129
#define IDC_EXTRA_ALPHABET				1130
#define IDC_IOC_ACT_TITLE               1131
#define IDC_IOC_ACT                     1132
#define IDC_IOC_EXP                     1133
#define IDC_ENT_ACT                     1134
#define IDM_FILE_SAVE                   40002
#define IDM_FILE_SAVE_MAP               40002
#define IDM_FILE_EXIT                   40003
#define IDM_EDIT_MAP                    40004
#define IDM_HELP_ABOUT                  40005
#define IDM_FILE_OPEN_MAP               40006
#define IDM_FILE_RELOAD                 40008
#define IDM_EDIT_OPTIONS                40009
#define IDM_SOLVE_OPTIONS               40009
#define IDM_SOLVE_TP_LOW                40010
#define IDM_SOLVE_TP_NORM               40011
#define IDM_SOLVE_TP_HIGH               40012
#define IDM_KEY_INIT                    40013
#define IDM_SOLVE_WORD                  40014
#define IDM_EDIT_UNDO                   40015
#define IDM_KEY_CLEAR                   40016
#define IDM_SOLVE_PATTERNS              40017
#define IDM_KEY_SCRAMBLE                40018
#define IDM_KEY_LOCK                    40019
#define IDM_KEY_LOCK_ALL                40020
#define IDM_EDIT_MSG                    40021
#define IDM_CIPHER_MERGE                40022
#define IDM_CIPHER_SIMPLIFY             40023
#define IDM_CIPHER_POLYIC               40024
#define IDM_CIPHER_RC_IOC               40025
#define IDM_FILE_SAVE_PLAIN             40026
#define IDM_CIPHER_ANAGRAM              40027
#define IDM_VIEW_DESELECT               40029
#define IDM_KEY_UNLOCK                  40030
#define IDM_KEY_UNLOCK_ALL              40031
#define IDM_VIEW_SYMGRAPH               40032
#define IDM_VIEW_LTRGRAPH               40033
#define IDM_VIEW_BYSTRING               40034
#define IDM_VIEW_BYFREQ                 40035
#define IDM_CIPHER_NGRAPHS              40036
#define IDM_FILE_COPY_PLAIN             40037
#define IDM_HELP_CONT                   40038
#define IDM_VIEW_LOCK_WORD              40039
#define IDM_CIPHER_RANDOM               40040
#define IDM_SOLVE_TP_IDLE               40041
#define IDM_CIPHER_HOMOSET              40042
#define IDM_VIEW_UNLOCK_WORD            40042
#define IDM_CIPHER_HORZ                 40043
#define IDM_CIPHER_VERT                 40044
#define IDM_CIPHER_REV                  40045
#define IDM_KEY_EXCLUDE                 40046
#define IDM_VIEW_EXCLUSIONS             40047
#define IDM_VIEW_MERGE_LOG              40049
#define IDM_VIEW_WORDS                  40050
#define IDM_KEY_CLEAR_EXCLUDE           40051
#define IDM_FILE_OPEN_ASC               40052
#define IDM_FILE_OPEN_NUM               40053
#define IDM_SOLVE_RESET                 40054
#define IDM_EDIT_REDO                   40055
#define IDM_CIPHER_SEQHOMO				40056
#define IDM_FILE_SAVE_CIPHER            40057
#define IDM_SOLVE_BRUTE					40058
#define IDM_SOLVE_INSERT                40059
#define IDM_KEY_INVERT_LOCK             40060
#define IDM_SOLVE_COPY_BEST             40061
#define UDM_DISPALL                     40100
#define UDM_DISPINFO                    40101
#define UDM_INIT_TOTAL                  40102
#define UDM_INIT_TARGET                 40103
#define UDM_HOMO_UPDATE                 40104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40043
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
